spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgresrootuser
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true